apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
  namespace: demo
spec:
  template:
    spec:
      containers:
      - name: job
        image: busybox
        command: ["/bin/sh", "-c", "echo Hello from Job; sleep 2"]
      restartPolicy: Never
  backoffLimit: 3
